"""products tables

Revision ID: cd8b9bfbcc83
Revises: 8724dfc41c1d
Create Date: 2020-06-28 11:30:59.802465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8b9bfbcc83'
down_revision = '8724dfc41c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_brands_brand_name'), 'brands', ['brand_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brands_brand_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
